/*
**    Generated by Code_Generation toolbox of Xcos with scilab-2024.0.0
**    Date : 13-Dec-2023
*/

/*---------------------------------------- Actuators */
void junk_code_actuator(int *flag, int *nport, int *nevprt, double *t, void *u, int *nu1, int *nu2, int *ut, int *flag1)
{
  int k = 0,l = 0;
}
/*---------------------------------------- Sensor */
void junk_code_sensor(int *flag, int *nport, int *nevprt, double *t, void *y, int *ny1, int *ny2, int *yt, int *flag1)
{
  int k = 0,l = 0;
}
